### ISSUE TITLE
Erro ao subir o container fastapi-app

### ISSUE THREAD

**Issue by mensageirodobem** [matheusgvieira/client-service#1]
Abaixo o log do container fastapi-app que não subiu com sucesso:

Passos:
1. Clone do repositório
2. docker compose -f "docker-compose.yml" up -d --build

2024-07-15 08:52:16 Traceback (most recent call last):
2024-07-15 08:52:16   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-07-15 08:52:16     sys.exit(main())
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
2024-07-15 08:52:16     return self.main(*args, **kwargs)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
2024-07-15 08:52:16     rv = self.invoke(ctx)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
2024-07-15 08:52:16     return ctx.invoke(self.callback, **ctx.params)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
2024-07-15 08:52:16     return __callback(*args, **kwargs)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 410, in main
2024-07-15 08:52:16     run(
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 577, in run
2024-07-15 08:52:16     server.run()
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 65, in run
2024-07-15 08:52:16     return asyncio.run(self.serve(sockets=sockets))
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2024-07-15 08:52:16     return loop.run_until_complete(main)
2024-07-15 08:52:16   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 69, in serve
2024-07-15 08:52:16     await self._serve(sockets)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76, in _serve
2024-07-15 08:52:16     config.load()
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 434, in load
2024-07-15 08:52:16     self.loaded_app = import_from_string(self.app)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 22, in import_from_string
2024-07-15 08:52:16     raise exc from None
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
2024-07-15 08:52:16     module = importlib.import_module(module_str)
2024-07-15 08:52:16   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-07-15 08:52:16     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-07-15 08:52:16   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2024-07-15 08:52:16 ModuleNotFoundError: No module named 'jwt_service'

**Comment by matheusgvieira** [comment]
Problema resolvido no commit https://github.com/matheusgvieira/client-service/commit/c734bdbd1085fd7957d222b6ea3cb0fe374cc318 

Obrigado! @mensageirodobem 

Se tiver tudo ok, peço que feche a issue.

**Comment by mensageirodobem** [comment]
Resolvido
